repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    - id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.8.0
    hooks:
    - id: isort
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the ref you want to point at
    hooks:
    - id: trailing-whitespace
    - id: check-case-conflict
    - id: check-added-large-files
    - id: check-merge-conflict

-   repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
    - id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      args: [
          --max-line-length=89,
          --max-complexity=18
          ]
      additional_dependencies: [
          pep8-naming,
          flake8-print
      ]