name: Deploy

on:
  push:
    branches: [ deploy-image-cicd]
  pull_request:
    branches: [ deploy-mage-cicd ]
  workflow_dispatch:

jobs:
  Build:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

      # Docker Layer caching
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
#       # Docker Layer Caching2
#     - name: Docker layer caching
#       uses: satackey/action-docker-layer-caching@v0.0.11
#       # Ignore the failure of a step and avoid terminating the job.
#       continue-on-error: true
#       with:
#         key: docker-layer-caching-${{ github.workflow }}-{hash}
#         restore-keys: docker-layer-caching-${{ github.workflow }}-
#         concurrency: 4
#         skip-save: true
          
    # Login to Docker Hub
    - name: docker hub login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
      # Create env file for passing environment veriables.
    - name: Create env file
      run: |
        touch .env        
        echo "DEV_ENV_FILE: ${{ secrets.DEV_ENV_FILE }}" >> .env
        cat .env
      # Build and Push image
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: peeyushweav/weav_data:develop
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
    
  DeployDev:
    name: Deploy to Dev 
    # if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
    
  DeployStaging:
    name: Deploy to Staging 
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
            
  DeployProd:
    name: Deploy to Production 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 